version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  server:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

volumes:
  mysql_data: