/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCDB_H_RPCGEN
#define _RPCDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sensor_data {
	int data_id;
	struct {
		u_int values_len;
		float *values_val;
	} values;
};
typedef struct sensor_data sensor_data;

struct user_data {
	struct sensor_data data;
	u_long key;
};
typedef struct user_data user_data;

struct del_data {
	int data_id;
	u_long key;
};
typedef struct del_data del_data;

struct read_data {
	int data_id;
	u_long key;
};
typedef struct read_data read_data;

struct response {
	char *resp;
};
typedef struct response response;

struct username {
	char *name;
};
typedef struct username username;

#define RPCDB_PROG 1
#define RPCDB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define login 1
extern  u_long * login_1(username *, CLIENT *);
extern  u_long * login_1_svc(username *, struct svc_req *);
#define load 2
extern  response * load_1(u_long *, CLIENT *);
extern  response * load_1_svc(u_long *, struct svc_req *);
#define store 3
extern  response * store_1(u_long *, CLIENT *);
extern  response * store_1_svc(u_long *, struct svc_req *);
#define add 4
extern  response * add_1(user_data *, CLIENT *);
extern  response * add_1_svc(user_data *, struct svc_req *);
#define del 5
extern  response * del_1(del_data *, CLIENT *);
extern  response * del_1_svc(del_data *, struct svc_req *);
#define update 6
extern  response * update_1(user_data *, CLIENT *);
extern  response * update_1_svc(user_data *, struct svc_req *);
#define read 7
extern  response * read_1(read_data *, CLIENT *);
extern  response * read_1_svc(read_data *, struct svc_req *);
#define get_stat 8
extern  response * get_stat_1(read_data *, CLIENT *);
extern  response * get_stat_1_svc(read_data *, struct svc_req *);
extern int rpcdb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define login 1
extern  u_long * login_1();
extern  u_long * login_1_svc();
#define load 2
extern  response * load_1();
extern  response * load_1_svc();
#define store 3
extern  response * store_1();
extern  response * store_1_svc();
#define add 4
extern  response * add_1();
extern  response * add_1_svc();
#define del 5
extern  response * del_1();
extern  response * del_1_svc();
#define update 6
extern  response * update_1();
extern  response * update_1_svc();
#define read 7
extern  response * read_1();
extern  response * read_1_svc();
#define get_stat 8
extern  response * get_stat_1();
extern  response * get_stat_1_svc();
extern int rpcdb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sensor_data (XDR *, sensor_data*);
extern  bool_t xdr_user_data (XDR *, user_data*);
extern  bool_t xdr_del_data (XDR *, del_data*);
extern  bool_t xdr_read_data (XDR *, read_data*);
extern  bool_t xdr_response (XDR *, response*);
extern  bool_t xdr_username (XDR *, username*);

#else /* K&R C */
extern bool_t xdr_sensor_data ();
extern bool_t xdr_user_data ();
extern bool_t xdr_del_data ();
extern bool_t xdr_read_data ();
extern bool_t xdr_response ();
extern bool_t xdr_username ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCDB_H_RPCGEN */
