/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcdb.h"

bool_t
xdr_sum_data (XDR *xdrs, sum_data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->resp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_username (XDR *xdrs, username *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	return TRUE;
}
