/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCDB_H_RPCGEN
#define _RPCDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_data {
	int x;
	int y;
};
typedef struct sum_data sum_data;

struct response {
	char *resp;
};
typedef struct response response;

struct username {
	char *name;
};
typedef struct username username;

#define RPCDB_PROG 1
#define RPCDB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define login 1
extern  response * login_1(username *, CLIENT *);
extern  response * login_1_svc(username *, struct svc_req *);
extern int rpcdb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define login 1
extern  response * login_1();
extern  response * login_1_svc();
extern int rpcdb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_data (XDR *, sum_data*);
extern  bool_t xdr_response (XDR *, response*);
extern  bool_t xdr_username (XDR *, username*);

#else /* K&R C */
extern bool_t xdr_sum_data ();
extern bool_t xdr_response ();
extern bool_t xdr_username ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCDB_H_RPCGEN */
