/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcdb.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpcdb_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		username login_1_arg;
		u_long load_1_arg;
		u_long store_1_arg;
		user_data add_1_arg;
		del_data del_1_arg;
		user_data update_1_arg;
		read_data read_1_arg;
		read_data get_stat_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case login:
		_xdr_argument = (xdrproc_t) xdr_username;
		_xdr_result = (xdrproc_t) xdr_u_long;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	case load:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) load_1_svc;
		break;

	case store:
		_xdr_argument = (xdrproc_t) xdr_u_long;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) store_1_svc;
		break;

	case add:
		_xdr_argument = (xdrproc_t) xdr_user_data;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case del:
		_xdr_argument = (xdrproc_t) xdr_del_data;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) del_1_svc;
		break;

	case update:
		_xdr_argument = (xdrproc_t) xdr_user_data;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) update_1_svc;
		break;

	case read:
		_xdr_argument = (xdrproc_t) xdr_read_data;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) read_1_svc;
		break;

	case get_stat:
		_xdr_argument = (xdrproc_t) xdr_read_data;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (char *(*)(char *, struct svc_req *)) get_stat_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPCDB_PROG, RPCDB_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCDB_PROG, RPCDB_VERS, rpcdb_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPCDB_PROG, RPCDB_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCDB_PROG, RPCDB_VERS, rpcdb_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPCDB_PROG, RPCDB_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
